# https://taskfile.dev

version: "3"

vars:
  LUA_EXTRACT_PATHS: ["rts/Lua/**/*.cpp", "rts/Rml/SolLua/**/*.cpp"]
  EXTRACTOR_VERSION: 3

tasks:
  extract-lua:
    summary: "Extracts lua meta files from the cpp files."
    dir: '{{ if not (empty .PATH_TO_ROOT) }}{{ .PATH_TO_ROOT }}{{ else }}/{{ end }}'
    cmds:
      - lua-doc-extractor {{.LUA_EXTRACT_PATHS | join " "}} --dest rts/Lua/library/generated
  install-tools:
    summary: "Installs needed tools for Lua docs extraction."
    cmds:
      - npm install -g lua-doc-extractor@{{.EXTRACTOR_VERSION}}
