# https://taskfile.dev

version: "3"

includes:
  base:
    taskfile: ../Taskfile.yml
    flatten: true

vars:
  TEMP_PATH: temp
  PATH_TO_ROOT: ../

tasks:
  generate-docs:
    deps: [extract-lua]
    summary: "Generates documentation for the website based on lua meta files."
    cmds:
      - emmylua_doc_cli -i rts/Lua/library -o {{.TEMP_PATH}} --override-template emmylua-doc-cli-template
      - python3 site/generate_from_meta.py {{.TEMP_PATH}} site/content/docs/lua-api
  install-site-tools:
    deps: [install-tools]
    summary: "Installs needed tools for Lua docs site generation."
    cmds:
      - cargo install emmylua_doc_cli
